### ISSUE TITLE
Various bug on some areas.

### ISSUE THREAD

**Issue by Yivan** [dachcom-digital/pimcore-toolbox#10] opened 2016-12-08 19:27 UTC
Hello! I tried the different areas proposed by your toolbox. Some are really great and usefull.
Thanks for sharing it with the community.

I tested them all and get some bugs on the followings. It occurs on the last stable Pimcore.

**Google Map**
The "Locations" button is not displayed in the editing panel on pimcore. If the googlemap editable is disrectly called from the view it is ok ($this->googlemap(...)), but as area the Location button is not displayed.

**Image**
There is not drag-and-drop zone for the image... maybe same problem than google, the image tag seems not rendered when called from the area. But strangely I have seen other area you made (like Snippet for instance) and the $this->image work ok.

**Slide Columns**
They didn't slide. So making 8 of them with 4 visible, only the 4 first are displayed on the backend, and in the frontend, the 4 first are displayed in a row, and the other 4 just below.
It is like the JS isn't triggered, but i checked, i have enabled the layout (as injecting the JS need this) and the static JS file are well just before the closing body tag (and are well loaded with OK 200).

**Parallax Container**
When adding this area, it try to getWidth() before we have the time to add an image ; ). See here please:
https://github.com/dachcom-digital/pimcore-toolbox/blob/master/views/scripts/toolbox/parallaxContainer/image.php#L33
So actually it could not be used. I forced the width to try it and after this, the image i have added doesn't appear in the frontend (maybe a JS problem too...).
But I have just before the close body tag the required library it seems:
```
<script type="text/javascript" src="/plugins/Toolbox/static/js/frontend/jquery.parallax-scroll.min.js"></script>
<script type="text/javascript" src="/plugins/Toolbox/static/js/frontend/vimeo-api.min.js"></script>
<script type="text/javascript" src="/plugins/Toolbox/static/js/frontend/toolbox.js"></script>
```

**Documentation**
Maybe you could add the following information, this will help next people ; ) :
- The layout must be activated (see https://www.pimcore.org/docs/latest/MVC/Template/Layouts.html)
- For Google Map you must manually add the Google JS library (`<script src="https://maps.googleapis.com/maps/api/js?key=YOUR_API_KEY" async defer></script>`)
- You can change default configuration of areas in the following files: `website/var/config/toolbox_configuration.php`

Thanks!

**Comment by solverat** [comment] 2017-02-26 16:44
**Google Map**
This has been fixed. Also the layout gets reorganized within 1.7 (see #14)

**Image**
We couldn't reproduce that one. try to update to the latest release.

**Slide Columns**
you need to wake them up by yourself. :) This toolbox plugin does not offer a full-service page builder but rather providing some basic modules. so you need to take care about javascript and frontend styling by yourself.

**Parallax Container**
This Module has been refactored from ground up (#15). please check out the [upgrade note](https://github.com/dachcom-digital/pimcore-toolbox/blob/master/UPGRADE.md) for 1.7 (will be released soon)

**Documentation**
You're right! A documentation is on its way to bring some light into the best practice darkness. :)

**Closed by solverat** 2017-02-26 16:44 UTC
Labels: help wanted
